# Generated by Django 3.2.18 on 2023-04-29 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='description',
            field=models.TextField(help_text='Введите текст описания', verbose_name='Описание'),
        ),
    ]
