# Generated by Django 3.2.18 on 2023-04-27 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscribe',
            options={'verbose_name': 'Кто на кого подписан', 'verbose_name_plural': 'Кто на кого подписан'},
        ),
    ]
